Add accelerate, new training loop
Almost trains, I have just made a mistake somewhere causing:

RuntimeError: Trying to backward through the graph a second time

I'm guessing it's because we need to do all the preprocessing in the dataloader rather than in the training loop.

Let me know any thoughts. It's getting close :-)